baseURL = ''
languageCode = 'en-us'
title = 'amelie makes art'
theme = 'hugo-starter-theme'

[params]
logo = ''

[menu]
[[menu.main]]
    identifier = 'about'
    name = 'about' #name shows up as the link in the menu
    url = '/about/'
    weight = -10
[[menu.main]]
    identifier = 'etsy shop'
    name = 'etsy shop'
    url = 'https://amelielavender.etsy.com'
    weight = -11
