baseURL = ''
languageCode = 'en-us'
title = 'amelie makes art'
theme = 'hugo-starter-theme'

[params]
    logo = '/test.png' #use with {{ with .Site.Params.authorPortrait }}
    authorPortrait = '/portrait_small.jpg'
[params.links]
    twitter = 'https://twitter.com/amelielavender'
    twitch = '' 
    tumblr = ''
    email = 'mailto:lavenderamelie@gmail.com'
    kofi = 'https://ko-fi.com/amelie'
    github = 'https://github.com/amelielavender/portfolio'
    fedi = 'https://a.sapphic.online'
    blog = '/blog'

[menu]
[[menu.main]]
    identifier = 'about' #ids links in case two entries have same name
    name = 'about' #name shows up as the link in the menu
    url = '/about/' #relative link
    weight = 0 #sort links by weight ascending.
[[menu.main]]
    identifier = 'etsy shop'
    name = 'etsy shop'
    url = 'https://amelielavender.etsy.com'
    weight = 100
[[menu.main]]
    identifier = 'comic'
    name = 'tomorrow mourning'
    url = '/comics/tomorrow-mourning'
    weight = 1
