baseURL = ''
languageCode = 'en'
title = 'amelie makes art'
theme = 'hugo-starter-theme'
enableEmoji = true
enableGitInfo = true

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English US'
    title = 'amelie makes art'
    weight = 0

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'

[params]
    description = 'amelie lavender is a US-based blind artist and illustrator.'
    images = ['https://ameliemakes.art/background.png']
    title = 'amelie makes art'
    header = '/artwork/illustration%20for%20eeveelution%20zine.png' #use with {{ with .Site.Params.authorPortrait }}
    logo = '/ameliemakesart-light.png'
    mainSections = ['blog',] # in case i want to add any other sections
[params.links]
    git = 'https://github.com/amelielavender/portfolio'

[menu]
[[menu.main]]
    identifier = 'about' #ids links in case two entries have same name
    name = 'about' #name shows up as the link in the menu
    url = '/about/' #relative link
    weight = 0 #sort links by weight ascending.
[[menu.main]]
    identifier = 'etsy shop'
    name = 'etsy shop'
    url = 'https://amelielavender.etsy.com'
    weight = 100
[[menu.main]]
    identifier = 'comic'
    name = 'tomorrow mourning'
    url = '/comics/tomorrow-mourning'
    weight = 1
[[menu.footer]]
    identifier = 'fedi'
    name = 'fedi'
    url = 'https://a.sapphic.online'
    weight = 1
[[menu.footer]]
    identifier = 'blog'
    name = 'blog'
    url = '/blog'
    weight = 2
[[menu.footer]]
    identifier = 'kofi'
    name = 'ko-fi'
    url = 'https://ko-fi.com/amelie'
    weight = 3
[[menu.footer]]
    identifier = 'etsy'
    name = 'etsy shop'
    url = 'https://etsy.com/amelielavender'
    weight = 4
